### PR TITLE
Add note on test_search failures

### PR DESCRIPTION
**Pull request by duncandewhurst**
@pindec fyi - as I mentioned, no need to worry about local `test_search` failures

### CODE REVIEW

**Review by jpmckinney — APPROVED** [review]

**Comment by jpmckinney** [comment]
Hmm, actually, the tests should pass anyway. I've instead added a troubleshooting section about updating dependencies and running `make clean` – which I think is what fixed it for you.

**Comment by duncandewhurst** [comment]
Even better, thanks!

**Comment by pindec** [comment]
Great, thanks both.

**Comment by duncandewhurst** [comment]
For some reason I cannot see https://github.com/open-contracting/standard-development-handbook/commit/f936ae15dca831276de9b948f41a4df442e6edb1 on https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/build.html

**Comment by jpmckinney** [comment]
Seems like a ReadTheDocs issue: https://github.com/readthedocs/readthedocs.org/issues/7911

I triggered a rebuild and the page is displaying correctly now.

**Pull request merged**
