### PR TITLE
Add instructions to export mappings csvs

### PR DESCRIPTION
**Pull request by duncandewhurst**

### CODE REVIEW

**Review by jpmckinney — COMMENTED** [review]
What does the user do once they have created the Excel spreadsheet?

Also, please:

- Fix capitalization (e.g. CSV)
- Add instructions for macOS (`brew install gnumeric`)

**Comment by jpmckinney** [comment]
Pinging on this. Also, does this create a single sheet, or a workbook with a sheet for each CSV?

**Comment by duncandewhurst** [comment]
My last commit includes updates to answer your questions!

**Comment by jpmckinney** [comment]
Thanks!

**Pull request merged**
