### PR TITLE
docs: add guidance about including images

### LINKED ISSUE #255: Document the process for incorporating images
This may include:
- The desired image format and size limits
- Where to put the editable version of the image and its translation

### PR DESCRIPTION
**Pull request by yolile**
closes #255

### CODE REVIEW

**Comment by yolile** [comment]
I guess we could add even more in terms of, for example, font types, that the image should have a transparent background, etc.

**Comment by jpmckinney** [comment]
I think it's fine as-is, which addresses our existing challenge - we can add more if those become an issue.

**Comment by yolile** [comment]
@jpmckinney seems that the indentation is not been shown correctly https://ocds-standard-development-handbook.readthedocs.io/en/latest/meta/style_guide.html#images

**Comment by jpmckinney** [comment]
Oops, need `#.` in RST.

**Comment by jpmckinney** [comment]
Pushed 658b0f2.

**Pull request merged**
